#!/bin/sh
SERVICE_NAME=VpLua
SERVER=server.lua
PID_NAME=VpLua-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_NAME ]; then
            nohup lua $SERVER > VpLua.log 2>&1 &
                        echo $! > $PID_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_NAME ]; then
            PID=$(cat $PID_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_NAME ]; then
            PID=$(cat $PID_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_NAME
            echo "$SERVICE_NAME starting ..."
            nohup lua $SERVER > VpLua.log 2>&1 &
                        echo $! > $PID_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac
